version: '3'
services:
  server:
    build: ./Container1
    container_name: server
    ports:
      - "20022:22"
      - "11211:11211"
    networks:
      - service

  client:
    build: ./Container2
    container_name: client
    ports:
    - "10022:22"
    networks:
      - service
    depends_on:
      - server

networks:
  service:
    driver: bridge
